/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lambda.dynamo;

import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;

import java.util.ArrayList;

public class Library {
    private DynamoDB dynamoDb;
    private String DYNAMODB_TABLE_NAME = "taskmaster";
    private Regions REGION = Regions.US_WEST_2;

    public boolean logMe(Context context) {
        LambdaLogger logger = context.getLogger();
        logger.log("This has been logged: " + context.toString());
        return true;

    }

    public Task saveTask(Task task, Context context) {

        final AmazonDynamoDB ddb = AmazonDynamoDBClientBuilder.defaultClient();
        DynamoDBMapper ddbMapper = new DynamoDBMapper(ddb);

        Task newTask = new Task(task.getId(), task.getTitle(), task.getDescription(), task.getAssignee(), task.getImage());

        if (task.getId() != null) {
            Task t = ddbMapper.load(Task.class, task.getId());

            ArrayList<HistoryObj> oldHistory = t.getHistory();
            HistoryObj newHistory = new HistoryObj(newTask.getStatus());
            oldHistory.add(newHistory);

            newTask.setHistory(oldHistory);
        } else {
            HistoryObj newHistory = new HistoryObj(newTask.getStatus());
            newTask.addHistory(newHistory);
        }
        ddbMapper.save(newTask);

        return newTask;

    }

}

